# Generated by Django 5.2.14 on 2026-06-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='building',
            field=models.CharField(blank=True, help_text='Building name / block', max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructions',
            field=models.TextField(blank=True, help_text='What to bring, dress code, etc.'),
        ),
        migrations.AddField(
            model_name='exam',
            name='room_number',
            field=models.CharField(blank=True, help_text='Room number or hall name', max_length=50),
        ),
        migrations.AddField(
            model_name='exam',
            name='seat_number',
            field=models.CharField(blank=True, help_text='Assigned seat or roll number range', max_length=100),
        ),
    ]
