# Generated by Django 5.2.14 on 2026-06-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_phone_verified_phoneverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
